# Generated by Django 3.0.4 on 2020-04-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200425_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
